### ISSUE TITLE
question

### ISSUE THREAD

**Issue by catchofu** [deepnox-io/docker-python-ta-lib#1]
Hi,
I want to use talib in my container's jupyter note book pull by docker, so I've pull the image of 9fevrier/python-ta-lib. Though I can run the container manually, I cannot run the image under the sugessted "docker run --name python-ta-lib -t 9fevrier/travis-python-ta-lib python3 -c 'import talib'", and got with below Err: 
Unable to find image '9fevrier/travis-python-ta-lib:latest' locally
docker: Error response from daemon: Head https://registry-1.docker.io/v2/9fevrier/travis-python-ta-lib/manifests/latest: Get https://auth.docker.io/token?account=catchofu&scope=repository%3A9fevrier%2Ftravis-python-ta-lib%3Apull&service=registry.docker.io: unexpected EOF.
How can I use the python-ta-lib in my jupyter note book? Would you please teach me?

**Comment by fmichaud** [comment]
Hello @catchofu,

It seems a documentation mistake...
I will check that as soon as possible.

Sorry for the inconvenience.

++

**Comment by fmichaud** [comment]
Hello @catchofu,

I fixed the documentation. Please use the command below :

```bash
docker run --name python-ta-lib -t 9fevrier/python-ta-lib python3 -c 'import talib'
```

Closed issue.

++
